CREATE TABLE IF NOT EXISTS urls (
id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
md5hash varchar(32) NOT NULL,
url TEXT NOT NULL,
response_status int NOT NULL,
headers TEXT NOT NULL,
body TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
INDEX (md5hash, response_status),
FULLTEXT (headers)
) ENGINE=InnoDB;